### ISSUE TITLE
ethereum not suppported

### ISSUE THREAD

**Issue by ramin1234** [daedalus/BreakingECDSAwithLLL#16]
i use web3 js for generate signature , with this code

for (var i=0;i<8;i++){
var a= await web3.eth.accounts.signTransaction({
    to: addr[i],
    value: valued[i],
    gas: 21000,
	nonce:686,
	gasPrice:gaspriced[i],
	chainId: 1,	
	data:0
}, '0x2EE0C4ED86CC5DAE5F593542783E9BE94E817FDD600903DD7499710175FDC2C6')
console.log(a.r+","+a.s+","+a.transactionHash)

writefile2(("1111,"+a.r+","+a.s+","+a.transactionHash+",0000"));
}

but when i test output with your code it cant find private key

**Comment by daedalus** [comment]
no support
