### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sokary2004** [daedalus/BreakingECDSAwithLLL#18]
File "/home/BreakingECDSAwithLLL/crack_weak_ECDSA_nonces_with_LLL.py", line 28, in load_csv
    if n < limit:
TypeError: '<' not supported between instances of 'int' and 'function'

**Comment by daedalus** [comment]
solved in [a0221d2](https://github.com/daedalus/BreakingECDSAwithLLL/commit/a0221d21d82d106641341b88d2433e19b90ddf95)
