### ISSUE TITLE
rnsn_inv' is not defined

### ISSUE THREAD

**Issue by seokchul-kwon** [daedalus/BreakingECDSAwithLLL#19]
hi bro,

I ran a new version that is now up, and the following error occurs:

Please check.

python3 crack_weak_ECDSA_nonces_with_LLL.py nonces.csv 176 6
Using: 6 sigs...
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "crack_weak_ECDSA_nonces_with_LLL.py", line 116, in <module>
    main()
  File "crack_weak_ECDSA_nonces_with_LLL.py", line 104, in main
    matrix = make_matrix(msgs,sigs,pubs)
  File "crack_weak_ECDSA_nonces_with_LLL.py", line 51, in make_matrix
    x0=(sigs[i][0] * modular_inv(sigs[i][1], order)) - rnsn_inv
NameError: name 'rnsn_inv' is not defined

cf) The first version that was uploaded worked well without any problems. Thank you.

**Comment by daedalus** [comment]
Please try now

**Comment by seokchul-kwon** [comment]
> Please try now

there is another error. 
I think it's a similar error, so please check it.

python3 crack_weak_ECDSA_nonces_with_LLL.py nonces.csv 176 6 | grep -e e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Using: 6 sigs...
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "crack_weak_ECDSA_nonces_with_LLL.py", line 117, in <module>
    main()
  File "crack_weak_ECDSA_nonces_with_LLL.py", line 105, in main
    matrix = make_matrix(msgs,sigs,pubs)
  File "crack_weak_ECDSA_nonces_with_LLL.py", line 61, in make_matrix
    matrix[m+0,i+1] = (int(2**B) / order)
NameError: name 'B' is not defined

**Comment by seokchul-kwon** [comment]
I additionally set all B values to 176 and ran it again, and this time, a similar error occurred.

 python3 crack_weak_ECDSA_nonces_with_LLL_B.py nonces.csv 6 | grep -e e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Using: 6 sigs...
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "crack_weak_ECDSA_nonces_with_LLL_B.py", line 118, in <module>
    main()
  File "crack_weak_ECDSA_nonces_with_LLL_B.py", line 110, in main
    keys = privkeys_from_reduced_matrix(new_matrix)
  File "crack_weak_ECDSA_nonces_with_LLL_B.py", line 75, in privkeys_from_reduced_matrix
    potential_priv_key = (sn * msgs[0]) - (sigs[0][1] * msgn) - (sigs[0][1] * sn * potential_nonce_diff)
NameError: name 'sn' is not defined

Please check overall so that it can work as well as the initial version. Thank you.

**Comment by daedalus** [comment]
finaly its working
