### ISSUE TITLE
Adding LSB Function

### ISSUE THREAD

**Issue by eychei** [daedalus/BreakingECDSAwithLLL#2]
Hi Daedalus,

Thanks for the nice python script.
I am trying to add LSB function to the code.

According to Nadia Heninger it is easy to use LSB by shifting the signatures by 2^-L bits.

I did the following in your code:
1. Generate bit shifted nonces:
nonces = [random.randrange(1, 2**bits) + yubikey_fixed_prefix for i in range(n)]
nonces_shift = [nonces[i] << 80 & mask for i in range(n)]

2. Shifting sigs in crack.py for a p192- curve and 192 bit length nonces:
      mask = 2 ** 192 - 1
      msgs.append(int(Z,16))
      sigs.append((int((bin(int(R,16) >> 80 & mask)),2),int((bin(int(S,16) >> 80 & mask)),2)))

So doing a left shift in the nonces to get 80-Bits 0s then right shift the sigs 80-bits to get the 0s MSB.

This does not work and the key is wrong.

Maybe you can help me out on this?

thx

**Comment by Pidberezkiy** [comment]
Hello Friend! Can you explain how You made it work, I cannot install the sage module. I'm using Ubuntu and python 3.8. Thanks.

**Comment by daedalus** [comment]
Done!
