### ISSUE TITLE
Error "sage.all_cmdline import *"

### ISSUE THREAD

**Issue by carloseduedu** [daedalus/BreakingECDSAwithLLL#3]
Hi, I first want to congratulate you for your work and contribution. For study purposes I implemented in Linux lll-VirtualBox 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

It turns out that the first script normally generates the csv containing data. 
But the second attack script returns the error below: 

lll@lll-VirtualBox:~/BreakingECDSAwithLLL$  python3 crack_weak_ECDSA_nonces_with_LLL.py nonces.csv 176 6 | grep -e 9ec4bc49e828d924af1d1029cacf709431abbde46d59554b62bc270e3b29c4b1
Traceback (most recent call last):
  File "crack_weak_ECDSA_nonces_with_LLL.py", line 11, in <module>
    from sage.all_cmdline import *
**ModuleNotFoundError: No module named 'sage'**

Do you have any idea what might be happening and how to solve it? Thanks

**Comment by daedalus** [comment]
It seems that sagemath is not properly installed in your system.
