### ISSUE TITLE
How to save generated keys (script attack crack_weak_ECDSA_nonces_with_LLL.py)  in a csv or txt file?

### ISSUE THREAD

**Issue by carloseduedu** [daedalus/BreakingECDSAwithLLL#4]
Hi, thanks again for your contribution.
I managed to implement (it really was the installation of sage, referring to the previous topic) thank you very much for the tip.
Now I need some help, I would like to save the "crack_weak_ECDSA_nonces_with_LLL.py" file output in txt or csv, but I can't change the script to do that. It only prints on the terminal... Could you give me a hand? Thanks

**Comment by daedalus** [comment]
The output is already text, you can postprocess it later piping it to your favorite tool.

I'm closing since there is no need to implement such a feature.
