### ISSUE TITLE
Your script doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by amiwrcd** [daedalus/BreakingECDSAwithLLL#6]
Hello @daedalus  I faced such problem. I have been using `Ubuntu 18.04` for calculations for a long time. It turned out that `SageMath` on `Ubuntu 18.04` does not support` Python 3`.
Higher `Ubuntu version` crashes on my PC. From here I have to use` Ubuntu 18.04` for calculations.
Your script is very great and I would like to rewrite it for `Python 2.7`, but unfortunately I poorly understand this language and do not know how to do it.
[I saw here previously opened similar questions.](https://github.com/daedalus/BreakingECDSAwithLLL/issues/5) I think I'm not the only one who faced this problem. Please help me fix your script to work in `Python 2.7`

**Comment by daedalus** [comment]
I only use Debian, no support sorry.
