### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Hurd8x** [daedalus/BreakingECDSAwithLLL#7]
Why this code not found privkey ?

thon3 weak_signature
_generator.py e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991
b7852b855 252 252 > nonces111.csv

/BreakingECDSAwithLLL$ python3 crack_weak_ECD
SA_nonces_with_LLL.py nonces111.csv  252 252 | grep -e e3b0c44298fc1c
149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

????

Help me please ?

Regard

**Comment by daedalus** [comment]
252 its a big number of unknown bits, try with lesser unknown bits and more sigs.

Ex:

python3 weak_signature_generator.py e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 250 60 > nonces.csv
python3 crack_weak_ECDSA_nonces_with_LLL.py nonces.csv 250 60 | grep -e e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Using: 60 sigs...
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
