### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hurd8x** [daedalus/BreakingECDSAwithLLL#8]
buntu@ip-172-31-65-90:~/BreakingECDSAwithLLL$ python3 weak_signature
_generator.py e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991
 250 60 >>60.txt

_--------_------------------------------------

ubuntu@ip-172-31-65-90:~/BreakingECDSAwithLLL$ python3 crack_weak_ECD
SA_nonces_with_LLL.py 60.txt 250 60 | grep -e e3b0c44298fc1c149afbf4c
8996fb92427ae41e4649b934ca495991b7852b855                            
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarnin
g: the imp module is deprecated in favour of importlib; see the modul
e's documentation for alternative uses                               
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, s
tat                                                                  
Traceback (most recent call last):                                   
  File "crack_weak_ECDSA_nonces_with_LLL.py", line 39, in <module>   
    msgs,sigs,pubs = load_csv(filename)                              
  File "crack_weak_ECDSA_nonces_with_LLL.py", line 32, in load_csv   
    tx,R,S,Z,pub = l                                                 
ValueError: too many values to unpack (expected 5)

How to fix this ?

Thanx

**Comment by daedalus** [comment]
For me works fine.

**Comment by Hurd8x** [comment]
Hmmm, were problem can be ?

**Comment by daedalus** [comment]
please check your system or try with another.

**Comment by Hurd8x** [comment]
250 bit nonce is good for me with 300 sigs. Thank you.
