### ISSUE TITLE
Short Nonces in ECDSA 

### ISSUE THREAD

**Issue by sberlinux** [daedalus/BreakingECDSAwithLLL#9]
Hello @daedalus It happens that some devices generate short Nonces. 
`Approximately 2 ^ 243-2 ^ 244`

Accordingly, if Nonces is short, then it must contain null at the beginning.
 That is, the first **3 bits** of Nonces contain a leading zero.

Given the known values of the signature `[R, S, H (e)]`, can we determine whether the size of Nonces is short?

Is there a way to find out information about the first **3 bit** of Nonces?

**Comment by daedalus** [comment]
That is not a bug, this program is not intended to break a specific device but to showcase LLL in general.
